export const LEMONMILK_REGULAR = 'LEMONMILK'
export const LEMONMILK_BOLD = 'LEMONMILK bold'
export const WONDER_UNIT_SANS_REGULAR = 'Wonder Unit Sans'
export const WONDER_UNIT_SANS_BOLD = 'Wonder Unit Sans bold'
export const HIRAGINO_KAKU_GOTHIC_PRO = 'Hiragino Kaku Gothic Pro'
export const CORPORATE_LOGO_ROUNDED = 'Corporate Logo Rounded'
